spring.application.name=spring_boot_project_ex

server.port=8080

#view
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#database connection
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##PROJECTDB9
spring.datasource.password=1234

#xml-location
mybatis.mapper-locations=classpath:mapper/**/*.xml
